# Generated by Django 2.1.4 on 2019-01-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_name', models.CharField(max_length=100)),
                ('artist_name', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('catal_number', models.CharField(max_length=20)),
                ('summary', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('audio', models.FileField(upload_to='audio/')),
            ],
        ),
    ]
