# Generated by Django 2.1.4 on 2019-01-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='beatport_link',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='deezer_link',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='soundcloud_link',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='spotify_link',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
