# Generated by Django 2.1.4 on 2019-01-13 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0003_remove_release_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release',
            name='release_date',
        ),
    ]
