# Generated by Django 2.0.2 on 2019-01-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0004_remove_release_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='itunes_link',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
