# Generated by Django 2.1.4 on 2019-01-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_title', models.CharField(max_length=200)),
                ('support_date', models.DateField()),
                ('support_summary', models.TextField()),
                ('support_image', models.ImageField(upload_to='images/')),
                ('catal_number', models.CharField(max_length=20)),
                ('release_link', models.CharField(max_length=100)),
            ],
        ),
    ]
