# Generated by Django 2.1.4 on 2019-01-13 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_auto_20190112_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='support',
            name='support_date',
        ),
    ]
