# Generated by Django 2.1.4 on 2019-01-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_remove_support_support_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supportimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_title', models.CharField(max_length=200)),
                ('support_summary', models.TextField()),
                ('support_image', models.ImageField(blank=True, upload_to='images/')),
                ('catal_number', models.CharField(max_length=20)),
                ('release_link', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='support',
            name='support_image',
        ),
    ]
