# Generated by Django 2.1.4 on 2019-01-13 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radio',
            name='podcast_date',
        ),
    ]
