# Generated by Django 2.1.4 on 2019-01-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Press',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('press_title', models.CharField(max_length=200)),
                ('press_summary', models.TextField()),
                ('press_image', models.ImageField(blank=True, upload_to='images/')),
                ('catal_number', models.CharField(max_length=20)),
                ('release_link', models.CharField(max_length=100)),
                ('press_link', models.CharField(max_length=100)),
            ],
        ),
    ]
